#!/usr/bin/env python3
"""Generate cuda_pointpillars_ros/include/params.h from the training config.

params.h is a DECODER for whatever the network emits. Every value in it must
mirror the config the model was trained and exported with -- class order, anchor
geometry, voxel grid, pillar capacity. Hand-maintaining that mirror is how this
project ended up decoding one model's output with another model's parameters and
getting confident nonsense out of it.

So: edit config/model.yaml, run this, never edit params.h.

    python3 tools/gen_params_h.py config/model.yaml \
        -o src/cuda_pointpillars_ros/include/params.h

Verify the generator itself with --check, which regenerates and diffs instead of
writing.
"""
import argparse
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required:  pip3 install pyyaml")

HEADER = """/*
 * SPDX-FileCopyrightText: Copyright (c) 2021 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
"""


def fmt(v):
    """Match the hand-written file: 0.16, -3.0, 1.57 -- no trailing zeros beyond one."""
    s = repr(float(v))
    return s[:-2] if s.endswith(".0") and abs(float(v)) >= 10 else s


def generate(cfg, generated_from):
    names = list(cfg["CLASS_NAMES"])
    pcr = [float(v) for v in cfg["POINT_CLOUD_RANGE"]]
    vs = [float(v) for v in cfg["VOXEL_SIZE"]]
    max_pts = int(cfg["MAX_POINTS_PER_VOXEL"])
    max_vox = int(cfg["MAX_NUMBER_OF_VOXELS"]["test"])
    layout = str(cfg.get("PILLAR_FEATURE_LAYOUT", "openpcdet10")).lower()
    if layout not in ("openpcdet10", "mmdet3d9"):
        sys.exit(f"PILLAR_FEATURE_LAYOUT must be openpcdet10 or mmdet3d9, got {layout!r}")
    mmdet9 = 1 if layout == "mmdet3d9" else 0
    nfeat = 9 if mmdet9 else 10

    # Anchors, in CLASS_NAMES order. Each class contributes one row per rotation,
    # laid out (dx, dy, dz, rotation) -- the order postprocess_kernels.cu reads
    # via anchor_ptr[0..3], and the order anchor_bottom_heights is indexed by
    # (ith_anchor / 2).
    by_name = {a["class_name"]: a for a in cfg["ANCHOR_GENERATOR_CONFIG"]}
    missing = [n for n in names if n not in by_name]
    if missing:
        sys.exit(f"ANCHOR_GENERATOR_CONFIG is missing entries for: {missing}")

    rot_counts = {len(by_name[n]["anchor_rotations"]) for n in names}
    if rot_counts != {2}:
        sys.exit(
            f"expected exactly 2 anchor_rotations per class (params.h hardcodes "
            f"num_anchors = num_classes * 2), got {rot_counts}")

    rows, bottoms = [], []
    for n in names:
        a = by_name[n]
        size = a["anchor_sizes"][0]
        if len(a["anchor_sizes"]) != 1:
            sys.exit(f"{n}: params.h supports one anchor_size per class")
        for rot in a["anchor_rotations"]:
            rows.append(f"      {fmt(size[0])},{fmt(size[1])},{fmt(size[2])},{fmt(rot)},")
        bottoms.append(fmt(a["anchor_bottom_heights"][0]))

    cls = " " + ",".join(f'"{n}"' for n in names) + ","
    out = [HEADER]
    out.append(f"""// GENERATED BY tools/gen_params_h.py FROM {generated_from} -- DO NOT EDIT.
// Edit the config and regenerate; hand edits will be silently overwritten and,
// worse, will desync this decoder from the model it decodes.
#ifndef PARAMS_H_
#define PARAMS_H_
const int MAX_VOXELS = {max_vox};
// Pillar feature layout. OpenPCDet's PillarVFE (USE_ABSLOTE_XYZ) builds 10
// channels; the mmdet3d-style implementation this repo's PyTorch model uses
// builds 9, which are a permutation of the same quantities. The CUDA feature
// kernel emits whichever this selects -- it MUST match the model's first conv.
#define PILLAR_FEATURE_LAYOUT_MMDET3D9 {mmdet9}
const int PILLAR_FEATURES = {nfeat};
class Params
{{
  public:
    static const int num_classes = {len(names)};
    const char *class_name [num_classes] = {{{cls}}};
    const float min_x_range = {fmt(pcr[0])};
    const float max_x_range = {fmt(pcr[3])};
    const float min_y_range = {fmt(pcr[1])};
    const float max_y_range = {fmt(pcr[4])};
    const float min_z_range = {fmt(pcr[2])};
    const float max_z_range = {fmt(pcr[5])};
    // the size of a pillar
    const float pillar_x_size = {fmt(vs[0])};
    const float pillar_y_size = {fmt(vs[1])};
    const float pillar_z_size = {fmt(vs[2])};
    const int max_num_points_per_pillar = {max_pts};
    const int num_point_values = 4;
    // the number of feature maps for pillar scatter
    const int num_feature_scatter = 64;
    const float dir_offset = 0.78539;
    const float dir_limit_offset = 0.0;
    // the num of direction classes(bins)
    const int num_dir_bins = 2;
    // anchors decode by (x, y, z, dir)
    static const int num_anchors = num_classes * 2;
    static const int len_per_anchor = 4;
    const float anchors[num_anchors * len_per_anchor] = {{
{chr(10).join(rows)}
      }};
    const float anchor_bottom_heights[num_classes] = {{{",".join(bottoms)},}};
    // the score threshold for classification
    const float score_thresh = {fmt(cfg.get("SCORE_THRESH", 0.1))};
    const float nms_thresh = {fmt(cfg.get("NMS_THRESH", 0.01))};
    // Candidate caps, mirroring the reference decode
    // (pointpillars.py::get_predicted_bboxes_single). nms_pre keeps only the
    // top-N ANCHORS by max class score before NMS; max_num caps the final list.
    // 0 disables either cap. Omitting them is what made this decoder emit more
    // than twice the reference's boxes.
    // Anchor grid placement -- see postprocess_kernels.cu. true = bin centres
    // (this repo's PyTorch model), false = endpoint-to-endpoint (OpenPCDet
    // default, NVIDIA's shipped model). Wrong choice offsets every box.
    const bool anchor_align_center = {str(bool(cfg.get("ANCHOR_ALIGN_CENTER", True))).lower()};
    const int nms_pre = {int(cfg.get("NMS_PRE", 100))};
    const int max_num = {int(cfg.get("MAX_NUM", 50))};
    const int max_num_pillars = MAX_VOXELS;
    const int pillarPoints_bev = max_num_points_per_pillar * max_num_pillars;
    // the detected boxes result decode by (x, y, z, w, l, h, yaw)
    const int num_box_values = 7;
    // the input size of the 2D backbone network
    const int grid_x_size = (max_x_range - min_x_range) / pillar_x_size;
    const int grid_y_size = (max_y_range - min_y_range) / pillar_y_size;
    const int grid_z_size = (max_z_range - min_z_range) / pillar_z_size;
    // the output size of the 2D backbone network
    const int feature_x_size = grid_x_size / 2;
    const int feature_y_size = grid_y_size / 2;
    Params() {{}};
}};
#endif""")

    # sanity: the grid must come out integral, or the network's feature map and
    # the decoder's idea of it silently disagree
    for axis, lo, hi, size in (("x", pcr[0], pcr[3], vs[0]), ("y", pcr[1], pcr[4], vs[1])):
        cells = (hi - lo) / size
        if abs(cells - round(cells)) > 1e-6:
            sys.exit(f"{axis} range {hi - lo} is not an integer multiple of voxel {size} "
                     f"({cells} cells) -- pick a range that divides exactly")
    return "".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("config")
    ap.add_argument("-o", "--output", default="src/cuda_pointpillars_ros/include/params.h")
    ap.add_argument("--check", action="store_true",
                    help="regenerate and diff against the existing file; do not write")
    args = ap.parse_args()

    with open(args.config) as f:
        cfg = yaml.safe_load(f)
    text = generate(cfg, args.config)

    if args.check:
        existing = open(args.output).read()
        if existing == text:
            print(f"OK: {args.output} matches {args.config}")
            return 0
        import difflib
        sys.stdout.writelines(difflib.unified_diff(
            existing.splitlines(True), text.splitlines(True),
            fromfile=args.output, tofile="generated"))
        return 1

    with open(args.output, "w") as f:
        f.write(text)
    print(f"wrote {args.output} from {args.config}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
